window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/23023094-78d85b58';
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.gwidget=window.__GOOGLEAPIS.gwidget||{};
window.__GOOGLEAPIS.gwidget.superbatch=false;window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plusone=window.__GOOGLEAPIS.iframes.plusone_m=window.__GOOGLEAPIS.iframes.plusone||{url:':socialhost:/u/:session_index:/_/+1/fastbutton',params:{count:'',size:'',url:''}};window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'http:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone'];(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload","superbatch":false},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/u/:session_index:/_/sharebox/dialog"},":socialhost:":"http://apis.google.com","profilecard":{"params":{"style":"#","m":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/appcard"},"plusone_m":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}},"plusone":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"chili.entities.starred.insert":{"cache":{"invalidates":["chili.entities.starred","chili.entitiesDefaultAcl"]}},"chili.people.get":true,"chili.entities.get":true,"pos.plusones.delete":true,"chili.entities.starred.delete":true,"chili.entities.list":true,"pos.plusones.get":true,"chili.groups.list":true,"pos.plusones.getDefaultAcl":{"cache":{"enabled":true}},"chili.entities.starred.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"chili.entitiesDefaultAcl.get":true,"chili.entities.starred.list":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"proxy":"https://clients6.google.com/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","jsh":"r;gc/23023094-78d85b58","auth":{"useInterimAuth":false}}});var jsloader=window.jsloader||{};
var gapi=window.gapi||{};
(function(){function g(){return window.___jsl=window.___jsl||{}}function n(b,d,a){a=l(a).join(b);h.length>0&&(a+=d+h.join(b));return a}function l(b){b.sort();for(var d=0,a,c;a=b[d];)a==c?b.splice(d,1):(c=a,++d);return b}function o(b,d){if(b&&d){if(g().c)throw"Cannot continue until a pending callback completes.";g().c=b;g().o=d}}function u(b){if((p||document.readyState)!="loading")return!1;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(b&&(b=b.sync,typeof b!="undefined"))return b;
for(var b=!1,d=document.getElementsByTagName("meta"),a=0,c;c=!b&&d[a];++a)"generator"==c.getAttribute("name")&&"blogger"==c.getAttribute("content")&&(b=!0);return b}function q(b,d){var a;a=b;if(f==="r")a=a.match(v);else{var c=a.match(w);if((a=g().m)&&c){var c=c[2],e=c.lastIndexOf(a);a=(e==0||a.charAt(0)=="."||c.charAt(e-1)==".")&&c.length-a.length==e}else a=!1}if(!a)throw"Cannot load url "+b+".";u(d)?document.write('<script src="'+b+'"><\/script>'):(a=document.createElement("script"),a.setAttribute("src",
b),document.getElementsByTagName("head")[0].appendChild(a))}function r(b,d){f="";h=[];i=window.console||window.opera&&window.opera.postError;j=b;p=d;var a,c=j.match(x)||j.match(y);try{a=c?decodeURIComponent(c[2]):g().h}catch(e){}a&&(a=a.split(";"),f=a.shift(),m=(c=f!=="r")?a.shift():"https://ssl.gstatic.com/webclient/js",k=a.shift(),s=(c=f==="d")&&a.shift()||"gcjs-3p",t=c&&a.shift()||"")}var x=/\?([^&#]*&)*jsh=([^&#]*)/,y=/#([^&]*&)*jsh=([^&]*)/,v=/^https:\/\/ssl.gstatic.com\/webclient\/js(\/[a-zA-Z0-9_\-]+)*\/[a-zA-Z0-9_\-\.:!]+\.js$/,
w=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?\//,f,m,s,t,k,h,i,j,p;r(document.location.href);jsloader.load=function(b,d){var a;if(!b||b.length==0)i&&i.warn("Cannot load empty features.");else if(f==="d"){var c=m+"/"+n(":","!",b);c+=".js?container="+s+"&c=2&jsload=0";k&&(c+="&r="+k);t=="d"&&(c+="&debug=1");a=c}else f==="r"||f==="f"?a=m+"/"+k+"/"+n("__","--",b)+".js":(c="Cannot respond for features ["+b.join(",")+"].",i&&i.warn(c));d=d||{};if(typeof d==="function"){var c=b,e=d;a?(o(e,1),q(a,void 0),h=l(h.concat(c))):
e&&e()}else{(g().cu=g().cu||[]).push(d.config);var e=d.callback,c=b,j=d;a?(o(e,1),q(a,j),h=l(h.concat(c))):e&&e()}};jsloader.reinitialize_=function(b,d){r(b,d)}})();
gapi.load=function(a,b){jsloader.load(a.split(":"),b)};(window.gapi=window.gapi||{}).load=gapi.load;
gapi.load('googleapis.client:plusone', {'callback': window['__bsld']  });