//v17 © 2011 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TIL=="undefined"){(function(){var Ja=function(){var h=document,l=h.body,p=h.documentElement,aa=eval("/*@cc_on!@*/false"),ba=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},v=ba("a",50),s=(Tynt.e||"")+"ic.tynt.com",oa=(Tynt.e||"")+"ac.tynt.com/?id="+v,t=function(){return(new Date).getTime()},D=function(a){return a.replace(/^\s+|\s+$/g,"")},M=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},w=function(a,b,c){a=h.createElement(a);M(b,a);M(c,a.style);return a},q,N;if(window.addEventListener){q=
function(a,b,c){a.addEventListener(b,c,false)};N=function(a,b,c){a.removeEventListener(b,c,false)}}else{q=function(a,b,c){a.attachEvent("on"+b,c)};N=function(a,b,c){a.detachEvent("on"+b,c)}}var O=function(a,b){var c=location.hostname.split("."),d=2;do{var f=c.slice(c.length-d,c.length).join(".");h.cookie=a+";path=/;domain=."+f+";"+b;d++}while(h.cookie.indexOf(a)==-1&&d<=c.length);if(h.cookie.indexOf(a)==-1)h.cookie=a+";path=/;"+b},P=function(a){h.readyState=="complete"?a():q(window,"load",function(){setTimeout(function(){if(typeof h.readyState==
"undefined"&&!aa)h.readyState="complete";a()},10)})},n=function(a,b){var c=[],d=function(f,e){var g="http://"+f.replace("id="+v,"id="+Tynt.join("~"));if(g.indexOf(s+"/b/p?")>-1&&typeof Tynt.b=="string")g+="&b="+Tynt.b;var k=new Image(1,1);if(e)k.onerror=e;k.src=g};n=function(f,e){c.push([f,e])};P(function(){n=d;for(var f=0;f<c.length;f++)n(c[f][0],c[f][1]);c=null});n(a,b)},ca=function(a){var b=[],c="",d;for(d in a)if(a.hasOwnProperty(d)){b.push(c,d,"=",a[d]);c="&"}return b.join("")},Q=function(a){for(var b=
0,c=a.length<100?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(Math.random()*3844);c=Math.abs(t()-12281184E5);return da(c,7)+da((b+a)%3844,2)},ea=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?ea(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},
da=function(a,b){var c=ea(a);return ba("0",b-c.length)+c},fa=function(a){return(a=D(a))?a.split(/\s+/i).length:0},R=D((h.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),ga=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")){a=a[b].getAttribute("href");b=location.protocol+"//"+location.host+location.pathname;var c=h.getElementsByTagName("base")[0];if(c)if(c=c.getAttribute("href"))b=
c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},E=function(a){return a.replace(/^https?:\/\//,"")},F=function(a,b){for(var c=b+"=",d=a.split(";"),f=0;f<d.length;f++){for(var e=d[f];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c)==0)return e.substring(c.length,e.length)}return null},pa=function(){var a=F(h.cookie,"tracertraffic"),b=encodeURIComponent(E(ga())),c=
h.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var d=s+"/b/p?id="+v+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+t(),f=d+(b?"&cu="+b:""),e=f+(h.referrer?"&r="+encodeURIComponent(E(h.referrer)):"");a=e+"&t="+encodeURIComponent(R);n(a,function(){n(e,function(){n(f,function(){n(d)})})})},qa=function(){var a=w("style",{type:"text/css",media:"print"}),b="#tyntPrint { background-image: url(http://"+s+"/b/h?id="+Tynt.join("~")+"&ts="+t()+")}";b=h.createTextNode(b);if(a.styleSheet)a.styleSheet.cssText=
b.nodeValue;else a.appendChild(b);h.getElementsByTagName("head")[0].appendChild(a);l.insertBefore(w("div",{id:"tyntPrint"}),l.firstChild)},S=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},ra=S(),sa=S(),ta=function(){var a,b=function(){window.removeEventListener("blur",b,false);T(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!=
"A"){window.addEventListener("blur",b,false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),ha=function(a){T(a.target||a.srcElement,true)},G,ia=function(a){a=a.target||a.srcElement;G=a.nodeName=="IMG"?a:null},U=function(){var a=function(g){return typeof g.pageX=="number"?{x:g.pageX-(p.scrollLeft?p.scrollLeft:l.scrollLeft),y:g.pageY-(p.scrollTop?p.scrollTop:l.scrollTop)}:{x:g.clientX,y:g.clientY}},b=function(g){g=a(g);return g.x<=0||g.y<=0||g.x>=l.clientWidth||g.y>=
l.clientHeight},c=function(g){g=a(g);return g.x<=0||g.y<=0||g.x>=p.clientWidth||g.y>=p.clientHeight},d=function(g){return g.target.nodeName=="#document"},f=function(g){g=a(g);return g.x<=4||g.y<=4||g.x>=p.clientWidth-4||g.y>=p.clientHeight-4},e=function(g){e=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?d:f;e(g)};return function(g){if(G&&e(g)){T(G);G=null}return true}}(),ua=function(){function a(j,m){if(o(j))n(s+"/b/o?id="+
v+(m?"&i=":"&l=")+encodeURIComponent(j)+"&ts="+t())}function b(j){var m=j.target||j.srcElement;if(j.button<2)for(;m&&m!=h;){j=m.href;if(m.nodeName=="A"&&j&&location.href.split("#")[0]!=j.split("#")[0]&&!/^javascript/i.test(j)){a(j);break}m=m.parentNode}}function c(){k&&a(k,true)}function d(j){j=j.target||j.srcElement;k=j.src||j.data||"flash";q(window,"blur",c)}function f(){k=null;N(window,"blur",c)}function e(j){q(j,"mouseover",d);q(j,"mouseout",f)}function g(){k&&a(k,true)}var k,o=S();q(document,
"mousedown",b);P(function(){for(var j=h.getElementsByTagName("iframe"),m=j.length-1;m>=0;m--){var r=j[m];if(r.src)e(r);else if(r.name)try{q(frames[r.name].document,"mousedown",b)}catch(u){}}j=h.getElementsByTagName("object");for(m=j.length-1;m>=0;m--)e(j[m])});q(window,"beforeunload",g);q(window,"unload",g)},x;if(Tynt.c)x=function(){};else{Tynt.c=true;x=function(){var a=true,b,c=function(d,f){var e={id:v,wc:fa(f),c:f,f:a?1:0,t:R};M(d,e);a=false;var g=e.trace_type;delete e.trace_type;var k=e.g;delete e.g;
for(var o=[],j=["id","wc","f","w","h","t","c"],m=0;m<j.length;m++){var r=j[m],u=e[r];u&&o.push([r,encodeURIComponent(u).replace(/\'/g,"%27")]);delete e[r]}for(var y in e)if(e.hasOwnProperty(y))(j=e[y])&&o.push([y,encodeURIComponent(j).replace(/\'/g,"%27")]);e=[];m=2048-(("http://"+s+"/a/t/x#?").length+(3+k.length)+5);r=o.length;var B=u=0,z=0,V,H,W,I,J=0;for(e[J]={g:k,tp:null};u<r&&e.length<35;){V=o[u][0];y=o[u][1];W=V.length+2;H=m-W-B;if(H>0){j=y.substring(z,z+H);I=j.slice(-2).indexOf("%");if(I>-1){j=
y.substring(z,z+H-2+I);B+=I+2}B+=j.length+W;z+=j.length;e[J][V]=j}else B=m;if(B>=m){e[++J]={g:k,p:J};B=0}if(z>=y.length){u++;z=0}}e[0].tp=e.length;n(s+"/b/t/"+g+"?"+ca(e[0]));for(k=1;k<e.length;k++)n(s+"/b/x/"+g+"?"+ca(e[k]))};/tynt=nout/.test(location.href)||ua();if(window.addEventListener){navigator.userAgent.match("Firefox/2")||l.addEventListener("copy",ha,false);window.addEventListener("mousedown",ia,false);window.addEventListener("dragleave",U,false);window.addEventListener("dragexit",U,false);
h.addEventListener("contextmenu",ta,false)}else{l.attachEvent("oncopy",ha);h.getElementsByTagName("html")[0].attachEvent("ondragleave",U);l.attachEvent("onmousedown",ia)}if(h.cookie.indexOf("tracertraffic=")!=-1)if(!h.referrer||h.referrer.indexOf(location.host)==-1)O("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");pa();n(oa);P(qa);return function(d,f){if(!h.getElementById("tyntSS")){var e;if(f)e=typeof getSelection!="undefined"?getSelection().toString():h.selection.createRange().text;var g=
d.src;g&&!e&&sa(g)&&c({g:Q(g),trace_type:3,w:d.width,h:d.height},g);if(e&&D(e).length&&d.nodeName!="TEXTAREA"&&d.nodeName!="INPUT"){g=ra(e);var k={trace_type:1};if(g)b=Q(e);k.g=b;var o=Tynt.m?Tynt.m(k,e):true;g&&o&&c(k,e)}}}}}var K=function(a){a=a.charCodeAt(0);return 3584<=a&&a<=3711||11904<=a&&a<=12591||12688<=a&&a<=40959||63744<=a&&a<=64255||65072<=a&&a<=65103||131072<=a&&a<=173791||194560<=a&&a<=195103},ja=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;b--){var c=a[b];
c.parentNode.removeChild(c)}},i,va=(Tynt.e||"")+"id.tynt.com",wa={t:3,p:6,w:7},A,X,Y,xa=["","Attribution","Attribution Share Alike","Attribution No Derivatives","Attribution Non-Commercial","Attribution Non-Commercial Share Alike","Attribution Non-Commercial No Derivatives"],ya=["","http://creativecommons.org/licenses/by/3.0","http://creativecommons.org/licenses/by-sa/3.0","http://creativecommons.org/licenses/by-nd/3.0","http://creativecommons.org/licenses/by-nc/3.0","http://creativecommons.org/licenses/by-nc-sa/3.0",
"http://creativecommons.org/licenses/by-nc-nd/3.0"],ka=function(a){a=a.match(/ixzz=?([^?$#]*)/);if(!a)return null;a=a[1].match(/&([^?$]*)/);if(Tynt.k)return Tynt.k.charAt(1);if(!a||!a[1])return null;return a[1]},Z=function(a){return(a=a.match(/axzz([^?$]*)/))&&a.length==2?a[1]:null},za=function(a){var b=ga();b=b?b:location.href;b=b.replace(/#(i|a)xzz=?(.*)$/g,"");return b+"#"+("ixzz"+a)},la=function(a){var b=new Date(t()+864E5);O("tracertraffic="+a.toString(),"expires="+b.toUTCString())},Aa=function(){var a=
location.href.match(/ixzz=?([^?&$#]*)/);if(a=(a&&a.length==2?a[1]:null)||Tynt.h){var b=ka(location.href);a=s+"/b/v?g="+a+(/\?trace_owner_view/.test(location.href)?"&o=y":"")+"&id="+v+(b?"&s="+b:"")+"&r="+encodeURIComponent(E(h.referrer))+"&ts="+t();n(a);return true}return false},Ba=function(a){n(s+"/b/a?g="+a+"&id="+v+"&r="+encodeURIComponent(E(h.referrer))+"&ts="+t(),function(){})},ma=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},C=false,Ca=function(a){if(C)return false;
C=true;var b="";if(i.a){var c=za(a),d='<a style="color: #003399;" href="';b+=i.ap;if(i.st)b=b+d+c+'">'+ma(R)+"</a> ";if(i.su)b=b+d+c+'">'+ma(c)+"</a>";if(i.as.length>0)b=b+"\n<br>"+i.as+" ";if(i.cc>0)b=b+"\n<br>Under Creative Commons License: "+d+ya[i.cc]+'">'+xa[i.cc]+"</a>"}if(i.el){if(b.length>0)b+="\n<br>";b+=i.el}if(A){if(b.length>0)b+="\n<br>";b=Y?b+X+d+"http://tcr"+i.s+".tynt.com/ads/"+Y+"/"+a+'">'+A+"</a>":b+X+d+"http://tcr"+i.s+".tynt.com/ads/"+A+"/"+$+"/"+a+'">'+A+"</a>"}var f,e;f=w("div",
{},{overflow:"hidden",color:"#000000",backgroundColor:"transparent",textAlign:"left",textDecoration:"none",border:"none"});if(!h.selection||!h.selection.createRange){a=getSelection();if(a.toString())if(typeof a.setBaseAndExtent!="undefined"){var g=a.getRangeAt(0);b=w("span",{innerHTML:b});if(i.t){b.innerHTML+="<br/><br/>";f.appendChild(b);f.appendChild(g.cloneContents())}else{f.appendChild(g.cloneContents());b.innerHTML="<br/><br/>"+b.innerHTML;f.appendChild(b)}ja(f);f.style.width=0.1;f.style.height=
0.1;f.style.position="absolute";f.style.top="-1000px";f.style.left="-1001px";f.appendChild(h.createElement("br"));b=f.innerText.length;l.insertBefore(f,l.firstChild);if(f.innerText.length!=b)f.style.overflow="";a.selectAllChildren(f);setTimeout(function(){f.parentNode.removeChild(f);getSelection().setBaseAndExtent(g.startContainer,g.startOffset,g.endContainer,g.endOffset);C=false},0)}else{e=w("div",{},{height:0,position:"absolute",top:"-1000px"});e.innerHTML="<br>";if(i.t){l.insertBefore(e,l.firstChild);
f.innerHTML=b+"<br><br>"}else{l.appendChild(e);f.innerHTML="<br>"+b+"<br>"}e.appendChild(f);b=h.createRange();b.selectNode(f);a.addRange(b);window.setTimeout(function(){e.parentNode.removeChild(e);C=false},0)}}else{var k=p.scrollLeft||l.scrollLeft,o=p.scrollTop||l.scrollTop;e=w("div",{},{overflow:"hidden",position:"absolute",left:k+20+"px",top:o+20+"px",width:"1px",height:"1px"});l.insertBefore(e,l.firstChild);var j=h.selection.createRange();f.innerHTML=i.t?b+"<br><br>"+j.htmlText:j.htmlText+"<br><br>"+
b;ja(f);e.appendChild(h.createElement("br"));e.appendChild(f);b=l.createTextRange();b.moveToElementText(f);b.select();setTimeout(function(){l.removeChild(e);if(j.text!=""){j.select();p.scrollLeft=k;l.scrollLeft=k;p.scrollTop=o;l.scrollTop=o}C=false},0)}return true},Da=function(a,b){var c=true;if(i.a||A||i.el){var d;d=D(b);if((d=d.length>=2?K(d.charAt(0))||K(d.charAt(d.length-1))||K(d.charAt(d.length/2)):K(d))&&b.length>14||!d&&fa(b)>7)if(i.a||A||i.el){c=Ca(a.g);if(i.a)a.trace_type=0}}return c},Ea=
function(a){var b=a?864E5:-5E3;b=new Date(t()+b);h.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},Ga=function(a){var b;a:{b=h.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=true;break a}b=false}if(!b&&Fa(location)){Tynt.b=a||Q(location.href);location.replace(location.href+"#axzz"+Tynt.b)}},Fa=function(a){if(a.hash!="")return false;if(typeof i.ba=="boolean"&&i.ba)i.ba=["/"];else if(!i.ba)return true;for(var b,c=i.ba.length-1;c>=0;c--){b=
null;var d=i.ba[c],f=d.indexOf("/");if(f!=0){b=d.slice(0,f);d=d.slice(f)}if(!b||a.host==b)if(d.charAt(d.length-1)=="#"){if(a.pathname.indexOf(d.slice(0,-1))==0)return false}else if(a.pathname==d)return false}return true},Ha=function(a){i=Tynt.i||window.tyntVariables||{};i.s=a.s||1;i.a=!(i.a==0||a.a==0);i.cc=i.cc||a.cc||0;if(i.cc>6)i.cc=0;i.b=!!(i.b||a.b);if(i.a){i.ap=(i.ap||(typeof tyntAP!="undefined"?tyntAP:null)||"Read more:")+" ";i.as=i.as||(typeof tyntAS!="undefined"?tyntAS:null)||"";i.st=!!(i.st||
a.st);i.su=!(i.su==0||a.su==0);i.sp=i.sp||a.sp;if(i.sp){Y=i.spid;X=(i.spt||decodeURIComponent(a.spt||""))+" ";A=i.sp||decodeURIComponent(a.sp||"")}}},na=function(){var a=h.title.indexOf("#ixzz");if(a>-1)h.title=h.title.substring(0,a);a=h.title.indexOf("#axzz");if(a>-1)h.title=h.title.substring(0,a)},Ia=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&Tynt[a].length==22)return Tynt[a];return null},L=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),d=0;d<c.length;d++){var f=
c[d].split("=");if(f[0].indexOf("amp;")==0)f[0]=f[0].substring(4);b[f[0]]=f[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=h.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),$=L.user||Ia();if(!$)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");L.user&&Tynt.push(L.user);if(!function(){var a=/tracer=test/.test(location.href);a&&n(va+"/script/verify/"+$);if(a)return true;
if(/tracer=no_tracing/.test(location.href))return true;if(/disableTracer=/.test(location.href)){a=location.href.match(/disableTracer=([^?$]*)/)[1];var b=new Date;b.setDate(a&&a=="on"?b.getDate()+365:b.getDate()-2);O("disableTracer=y","expires="+b.toUTCString());b=w("div",{},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+
(a&&a=="on"?"off":"on")+" in this browser.<br>You may close this window.";l.insertBefore(b,l.firstChild);return true}if(F(h.cookie,"disableTracer"))return true;return false}()){if(aa){na();h.attachEvent("onpropertychange",na)}Ha(L);var T=x();x=wa[ka(location.href)];if(Aa()){x||(x=/tynt.com/.test(h.referrer)?3:1);la(x)}Tynt.m=Da;if(i.b)if(Z=Z(location.href)){if("#axzz"+F(h.cookie,"tracerabg")!=location.hash){Ba(Z);la(2)}}else{Ga(F(h.cookie,"tracerabg"));Ea(Tynt.b)}}};Tynt.TIL=function(){document.body?
Ja():setTimeout(Tynt.TIL,300)}})();Tynt.TIL()};
